name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: .NET SDK’yı Kur
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Bağımlılıkları Yükle
        run: dotnet restore

      - name: Projeyi Derle
        run: dotnet build --configuration Release --no-restore

      - name: Testleri Çalıştır
        run: dotnet test --no-restore --verbosity normal
